<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://www.w3.org/2000/09/xmldsig#"
           targetNamespace="http://www.w3.org/2000/09/xmldsig#"
           elementFormDefault="qualified">

  <xs:element name="Signature" type="SignatureType"/>
  <xs:complexType name="SignatureType">
    <xs:sequence>
      <xs:element name="SignedInfo" type="SignedInfoType"/>
      <xs:element name="SignatureValue" type="SignatureValueType"/>
      <xs:element name="KeyInfo" type="KeyInfoType" minOccurs="0"/>
      <xs:element name="Object" type="ObjectType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="Id" type="xs:ID" use="optional"/>
  </xs:complexType>

  <xs:complexType name="SignedInfoType">
    <xs:sequence>
      <xs:element name="CanonicalizationMethod" type="CanonicalizationMethodType"/>
      <xs:element name="SignatureMethod" type="SignatureMethodType"/>
      <xs:element name="Reference" type="ReferenceType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="Id" type="xs:ID" use="optional"/>
  </xs:complexType>

  <xs:complexType name="CanonicalizationMethodType">
    <xs:sequence>
      <xs:any namespace="##any" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
    </xs:sequence>
    <xs:attribute name="Algorithm" type="xs:anyURI" use="required"/>
  </xs:complexType>

  <xs:complexType name="SignatureMethodType">
    <xs:sequence>
      <xs:any namespace="##any" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
      <xs:element name="HMACOutputLength" type="xs:int" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="Algorithm" type="xs:anyURI" use="required"/>
  </xs:complexType>

  <xs:complexType name="ReferenceType">
    <xs:sequence>
      <xs:element name="Transforms" type="TransformsType" minOccurs="0"/>
      <xs:element name="DigestMethod" type="DigestMethodType"/>
      <xs:element name="DigestValue" type="xs:base64Binary"/>
    </xs:sequence>
    <xs:attribute name="Id" type="xs:ID" use="optional"/>
    <xs:attribute name="URI" type="xs:anyURI" use="optional"/>
    <xs:attribute name="Type" type="xs:anyURI" use="optional"/>
  </xs:complexType>

  <xs:complexType name="TransformsType">
    <xs:sequence>
      <xs:element name="Transform" type="TransformType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TransformType">
    <xs:sequence>
      <xs:any namespace="##any" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
      <xs:element name="XPath" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="Algorithm" type="xs:anyURI" use="required"/>
  </xs:complexType>

  <xs:complexType name="DigestMethodType">
    <xs:sequence>
      <xs:any namespace="##any" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
    </xs:sequence>
    <xs:attribute name="Algorithm" type="xs:anyURI" use="required"/>
  </xs:complexType>

  <xs:complexType name="SignatureValueType">
    <xs:simpleContent>
      <xs:extension base="xs:base64Binary">
        <xs:attribute name="Id" type="xs:ID" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="KeyInfoType">
    <xs:sequence>
      <xs:element name="KeyName" type="xs:string" minOccurs="0"/>
      <xs:element name="KeyValue" type="KeyValueType" minOccurs="0"/>
      <xs:element name="RetrievalMethod" type="RetrievalMethodType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="X509Data" type="X509DataType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="PGPData" type="PGPDataType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="SPKIData" type="SPKIDataType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="MgmtData" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
    </xs:sequence>
    <xs:attribute name="Id" type="xs:ID" use="optional"/>
  </xs:complexType>

  <xs:complexType name="KeyValueType">
    <xs:choice>
      <xs:element name="DSAKeyValue" type="DSAKeyValueType"/>
      <xs:element name="RSAKeyValue" type="RSAKeyValueType"/>
      <xs:any namespace="##other" processContents="lax"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="DSAKeyValueType">
    <xs:sequence>
      <xs:element name="P" type="CryptoBinary"/>
      <xs:element name="Q" type="CryptoBinary"/>
      <xs:element name="G" type="CryptoBinary" minOccurs="0"/>
      <xs:element name="Y" type="CryptoBinary"/>
      <xs:element name="J" type="CryptoBinary" minOccurs="0"/>
      <xs:element name="Seed" type="CryptoBinary" minOccurs="0"/>
      <xs:element name="PgenCounter" type="CryptoBinary" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="RSAKeyValueType">
    <xs:sequence>
      <xs:element name="Modulus" type="CryptoBinary"/>
      <xs:element name="Exponent" type="CryptoBinary"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="RetrievalMethodType">
    <xs:sequence>
      <xs:element name="Transforms" type="TransformsType" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="URI" type="xs:anyURI" use="required"/>
    <xs:attribute name="Type" type="xs:anyURI" use="optional"/>
  </xs:complexType>

  <xs:complexType name="X509DataType">
    <xs:sequence>
      <xs:element name="X509IssuerSerial" type="X509IssuerSerialType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="X509SKI" type="xs:base64Binary" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="X509SubjectName" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="X509Certificate" type="xs:base64Binary" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="X509CRL" type="xs:base64Binary" minOccurs="0" maxOccurs="unbounded"/>
      <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="X509IssuerSerialType">
    <xs:sequence>
      <xs:element name="X509IssuerName" type="xs:string"/>
      <xs:element name="X509SerialNumber" type="xs:integer"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="PGPDataType">
    <xs:sequence>
      <xs:choice>
        <xs:sequence>
          <xs:element name="PGPKeyID" type="xs:base64Binary"/>
          <xs:element name="PGPKeyPacket" type="xs:base64Binary" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:sequence>
          <xs:element name="PGPKeyPacket" type="xs:base64Binary" maxOccurs="unbounded"/>
          <xs:element name="PGPKeyID" type="xs:base64Binary" minOccurs="0"/>
        </xs:sequence>
      </xs:choice>
      <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="SPKIDataType">
    <xs:sequence>
      <xs:element name="SPKISexp" type="xs:base64Binary" maxOccurs="unbounded"/>
      <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ObjectType">
    <xs:sequence>
      <xs:any namespace="##any" minOccurs="0" maxOccurs="unbounded" processContents="lax"/>
    </xs:sequence>
    <xs:attribute name="Id" type="xs:ID" use="optional"/>
    <xs:attribute name="MimeType" type="xs:string" use="optional"/>
    <xs:attribute name="Encoding" type="xs:anyURI" use="optional"/>
  </xs:complexType>

  <xs:simpleType name="CryptoBinary">
    <xs:restriction base="xs:base64Binary"/>
  </xs:simpleType>

</xs:schema>